#!/usr/bin/python
#
#    testdrive-select-iso - present a list and select an ISO for testdriving
#    Copyright (C) 2009 Canonical Ltd.
#    Copyright (C) 2009 Dustin Kirkland
#
#    Authors: Dustin Kirkland <kirkland@canonical.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 3 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.


import commands, time, os

PKG = "testdrive"
ARCH = commands.getoutput("uname -m | grep -qs x86_64 && echo amd64 || echo i386")
RELEASE = "lucid"

ISO = []
ISO.append({"name":"Ubuntu Desktop", "url":"rsync://cdimage.ubuntu.com/cdimage/daily-live/current/%s-desktop-%s.iso"%(RELEASE,ARCH)})
ISO.append({"name":"Ubuntu Server", "url":"rsync://cdimage.ubuntu.com/cdimage/ubuntu-server/daily/current/%s-server-%s.iso"%(RELEASE,ARCH)})
ISO.append({"name":"Ubuntu Alternate", "url":"rsync://cdimage.ubuntu.com/cdimage/daily/current/%s-alternate-%s.iso"%(RELEASE,ARCH)})
ISO.append({"name":"Ubuntu DVD", "url":"rsync://cdimage.ubuntu.com/cdimage/dvd/current/%s-dvd-%s.iso"%(RELEASE,ARCH)})
ISO.append({"name":"Ubuntu Netbook Remix", "url":"rsync://cdimage.ubuntu.com/cdimage/ubuntu-netbook-remix/daily-live/current/%s-netbook-remix-i386.iso"%(RELEASE)})

# These are problematic, because the names are all the same ... lucid-desktop-i386.iso
# Need to rename the destination ISO accordingly
#rsync://cdimage.ubuntu.com/cdimage/kubuntu/daily-live/current/%s-desktop-%s.iso
#rsync://cdimage.ubuntu.com/cdimage/xubuntu/daily-live/current/%s-desktop-%s.iso
#rsync://cdimage.ubuntu.com/cdimage/mythbuntu/daily-live/current/%s-desktop-%s.iso
#rsync://cdimage.ubuntu.com/cdimage/kubuntu-netbook/daily-live/current/%s-netbook-i386.iso"

i = 1
for iso in ISO:
	print("  %d. %s (%s)" % (i, iso["name"], RELEASE))
	filename = os.path.basename(iso["url"])
	path = "%s/.cache/%s/%s" % (os.environ["HOME"], PKG, filename)
	if os.path.exists(path):
		print("     +--> [%s] %s" % (time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(os.path.getmtime(path))), filename))
	i=i+1
choice = int(raw_input("\nSelect an ISO to testdrive: "))
if choice in range(1, i):
	print(ISO[choice]["url"])
else:
	print("Invalid selection")
